services:
  solana-monitor:
    container_name: solana-monitor
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: monitor-image:latest
    network_mode: "host"
    volumes:
      - /root/.local/share/solana/install/active_release/bin:/solana
      - ~/.config/solana:/root/.config/solana
      - app_logs:/app/logs
      - ./config.yml:/app/config.yml
    environment:
      - PATH=/solana:$PATH
      - TZ=Europe/Moscow

  promtail:
    container_name: promtail
    restart: unless-stopped
    image: grafana/promtail
    volumes:
      - ./promtail.yml:/etc/agent/agent.yaml
      - /root/solana/solana.log:/var/log/solana.log
      - app_logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    command:
      - --config.file=/etc/agent/agent.yaml

  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  node-exporter:
    container_name: node-exporter
    restart: unless-stopped
    image: prom/node-exporter:latest
    network_mode: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

networks:
  solana-monitor_monitoring:
    external: true

volumes:
  app_logs:
  prometheus_data:

